### ISSUE TITLE
No matching distribution found for `onnxruntime-directml`

### ISSUE THREAD

**Issue by NatoBoram** [RVC-Project/Retrieval-based-Voice-Conversion-WebUI#1109]
In [Preparing the environment](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/README.en.md#preparing-the-environment), it is indicated to run this command:

```sh
pip install -r requirements-dml.txt
```

However, it gives this error:

```yaml
ERROR: Could not find a version that satisfies the requirement onnxruntime-directml (from versions: none)
ERROR: No matching distribution found for onnxruntime-directml
```

### Workaround

One workaround is to `xargs` each requirement into `pip install`.

```sh
cat requirements-dml.txt | xargs -I _ pip install _
```

### References

* Related to https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1053

### System information

```yaml
OS: Pop!_OS 22.04 LTS x86_64 
Host: MS-7D53 1.0 
Kernel: 6.4.6-76060406-generic 
Shell: zsh 5.8.1 
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
GPU: AMD ATI Radeon RX 6700 XT
Memory: 32007MiB 
```

```sh
Python 3.10.13
```
